name: Build and Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/counter-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/counter-app:latest

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          # EC2_HOST도 깃허브 셋팅에서 환경변수 추가
          HOST: ${{ secrets.EC2_HOST }}
        run: |
          # 키 파일 생성
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          # docker-compose.yml 전송
          scp -i key.pem -o StrictHostKeyChecking=no \
          docker-compose.yml ubuntu@$HOST:/home/ubuntu/
          # nginx.conf도 전송
          scp -i key.pem -o StrictHostKeyChecking=no \
          nginx.conf ubuntu@$HOST:/home/ubuntu/
          # 깃허브 서버에서 EC2 원격 접속 및 배포
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@$HOST << 'EOF'
            cd ~
            docker-compose down
            docker-compose pull
            docker-compose up -d --scale app=1 # 스케일링 1개만
            docker-compose restart nginx
          EOF